### ISSUE TITLE
Cannot find scripts to generate LB803 and LB804 feature

### ISSUE THREAD

**Issue by Superhzf** [KazukiOnodera/Home-Credit-Default-Risk#1]
Hi Onodera,

Thanks for your great work for this problem. I am trying to learn from your great work and I know that you generated two important feature sets LB803 and LB804, I read your scripts but could not find any scripts that finally generate those two. I can only find a script to generate CV805_LB803.

Could you please give me some clue on this?

**Comment by KazukiOnodera** [comment]
Sorry for bothering you.
Actually, I didn't clean up this git, but I wouldn't do any further.

**Comment by Superhzf** [comment]
Hi Onodera,

No worries at all! I have learned a lot from your git, thank you so much!
